name: Deploy a EKS
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to ECR
        run: |
          docker build -t tienda-backend .
          docker tag tienda-backend:latest 757858572974.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest
          docker push 757858572974.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest
      - name: Deploy to EKS
        run: |
          kubectl apply -f backend.yaml